<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="cust.aspx.cs" Inherits="FypWeb.cust" %>


<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">

    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css2/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	  <form id="form1" runat="server">
  	<div class="header">
	     <div class="container">
            
	        <div class="row">
	           <div class="col-md-5">
	              <div class="logo">
	              <!-- Logo -->
	                 <h1><a href="index.html">Admin Panel</a></h1>
	              </div>
	           </div>
	          
	           <div class="col-md-6">
	              <div class="navbar navbar-inverse" role="banner" >
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	                    <ul class="nav navbar-nav">
	                     
	                    </ul>
	                  </nav>
	              </div>
	           </div>
	        </div>
	     </div>
	</div>

    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li><a href="AdminPanel.aspx"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>

                    <li class="submenu">
                         <a href="#">
                            <i class="glyphicon glyphicon-list"></i> Tables
                            <span class="caret pull-right"></span>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                            <li><a href="cust.aspx">Customers</a></li>
                            <li><a href="emp.aspx">Employees</a></li>
                             <li><a href="en.aspx">Entertainers</a></li>
                             <li><a href="FoodItems.aspx">Food Items</a></li>
                             <li><a href="Venues.aspx">Venues</a></li>
                             <li><a href="VenueSchedule.aspx">Venue Schedule</a></li>
                             

                        </ul>
                    </li>
                </ul>
             </div>
		  </div>
		  <div class="col-md-10">

		  	<div class="row">
  				
  					<div class="content-box-large" >
		  				<div class="panel-heading">
							<div class="panel-title"><h3>Customers</h3></div>
							
									<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="CustID" DataSourceID="SqlDataSource1" GridLines="Vertical" Font-Bold="True" Font-Size="Small">
                                        <AlternatingRowStyle BackColor="#DCDCDC" />
                                <Columns>
                                    <asp:BoundField DataField="CustID" HeaderText="CustID" InsertVisible="False" ReadOnly="True" SortExpression="CustID" />
                                    <asp:BoundField DataField="CustName" HeaderText="CustName" SortExpression="CustName" />
                                    <asp:BoundField DataField="CustCNIC" HeaderText="CustCNIC" SortExpression="CustCNIC" />
                                    <asp:BoundField DataField="CustPOBox" HeaderText="CustPOBox" SortExpression="CustPOBox" />
                                    <asp:BoundField DataField="CustCity" HeaderText="CustCity" SortExpression="CustCity" />
                                    <asp:BoundField DataField="CustStatus" HeaderText="CustStatus" SortExpression="CustStatus" />
                                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                                    <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
                                    <asp:BoundField DataField="Contact" HeaderText="Contact" SortExpression="Contact" />
                                </Columns>
                                <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                                <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                                <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                <SortedAscendingHeaderStyle BackColor="#0000A9" />
                                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                <SortedDescendingHeaderStyle BackColor="#000065" />
                            </asp:GridView>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:OnClickEventsConnectionString2 %>" DeleteCommand="DELETE FROM [Customers] WHERE [CustID] = @original_CustID " InsertCommand="INSERT INTO [Customers] ([CustName], [CustAddress], [CustDOB], [CustAccountNo], [CustCNIC], [CustPOBox], [CustCity], [CustStatus], [Password], [Email], [Username], [Contact]) VALUES (@CustName, @CustAddress, @CustDOB, @CustAccountNo, @CustCNIC, @CustPOBox, @CustCity, @CustStatus, @Password, @Email, @Username, @Contact)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Customers]" UpdateCommand="UPDATE [Customers] SET [CustName] = @CustName, [CustAddress] = @CustAddress, [CustDOB] = @CustDOB, [CustAccountNo] = @CustAccountNo, [CustCNIC] = @CustCNIC, [CustPOBox] = @CustPOBox, [CustCity] = @CustCity, [CustStatus] = @CustStatus, [Password] = @Password, [Email] = @Email, [Username] = @Username, [Contact] = @Contact WHERE [CustID] = @original_CustID AND [CustName] = @original_CustName AND [CustAddress] = @original_CustAddress AND (([CustDOB] = @original_CustDOB) OR ([CustDOB] IS NULL AND @original_CustDOB IS NULL)) AND (([CustAccountNo] = @original_CustAccountNo) OR ([CustAccountNo] IS NULL AND @original_CustAccountNo IS NULL)) AND (([CustCNIC] = @original_CustCNIC) OR ([CustCNIC] IS NULL AND @original_CustCNIC IS NULL)) AND (([CustPOBox] = @original_CustPOBox) OR ([CustPOBox] IS NULL AND @original_CustPOBox IS NULL)) AND [CustCity] = @original_CustCity AND (([CustStatus] = @original_CustStatus) OR ([CustStatus] IS NULL AND @original_CustStatus IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([Username] = @original_Username) OR ([Username] IS NULL AND @original_Username IS NULL)) AND (([Contact] = @original_Contact) OR ([Contact] IS NULL AND @original_Contact IS NULL))">
                                <DeleteParameters>
                                    <asp:Parameter Name="original_CustID" Type="Int32" />
                                    <asp:Parameter Name="original_CustName" Type="String" />
                                    <asp:Parameter Name="original_CustAddress" Type="String" />
                                    <asp:Parameter Name="original_CustDOB" Type="String" />
                                    <asp:Parameter Name="original_CustAccountNo" Type="Int64" />
                                    <asp:Parameter Name="original_CustCNIC" Type="Int64" />
                                    <asp:Parameter Name="original_CustPOBox" Type="Int32" />
                                    <asp:Parameter Name="original_CustCity" Type="String" />
                                    <asp:Parameter Name="original_CustStatus" Type="String" />
                                    <asp:Parameter Name="original_Password" Type="String" />
                                    <asp:Parameter Name="original_Email" Type="String" />
                                    <asp:Parameter Name="original_Username" Type="String" />
                                    <asp:Parameter Name="original_Contact" Type="String" />
                                </DeleteParameters>
                                <InsertParameters>
                                    <asp:Parameter Name="CustName" Type="String" />
                                    <asp:Parameter Name="CustAddress" Type="String" />
                                    <asp:Parameter Name="CustDOB" Type="String" />
                                    <asp:Parameter Name="CustAccountNo" Type="Int64" />
                                    <asp:Parameter Name="CustCNIC" Type="Int64" />
                                    <asp:Parameter Name="CustPOBox" Type="Int32" />
                                    <asp:Parameter Name="CustCity" Type="String" />
                                    <asp:Parameter Name="CustStatus" Type="String" />
                                    <asp:Parameter Name="Password" Type="String" />
                                    <asp:Parameter Name="Email" Type="String" />
                                    <asp:Parameter Name="Username" Type="String" />
                                    <asp:Parameter Name="Contact" Type="String" />
                                </InsertParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="CustName" Type="String" />
                                    <asp:Parameter Name="CustAddress" Type="String" />
                                    <asp:Parameter Name="CustDOB" Type="String" />
                                    <asp:Parameter Name="CustAccountNo" Type="Int64" />
                                    <asp:Parameter Name="CustCNIC" Type="Int64" />
                                    <asp:Parameter Name="CustPOBox" Type="Int32" />
                                    <asp:Parameter Name="CustCity" Type="String" />
                                    <asp:Parameter Name="CustStatus" Type="String" />
                                    <asp:Parameter Name="Password" Type="String" />
                                    <asp:Parameter Name="Email" Type="String" />
                                    <asp:Parameter Name="Username" Type="String" />
                                    <asp:Parameter Name="Contact" Type="String" />
                                    <asp:Parameter Name="original_CustID" Type="Int32" />
                                    <asp:Parameter Name="original_CustName" Type="String" />
                                    <asp:Parameter Name="original_CustAddress" Type="String" />
                                    <asp:Parameter Name="original_CustDOB" Type="String" />
                                    <asp:Parameter Name="original_CustAccountNo" Type="Int64" />
                                    <asp:Parameter Name="original_CustCNIC" Type="Int64" />
                                    <asp:Parameter Name="original_CustPOBox" Type="Int32" />
                                    <asp:Parameter Name="original_CustCity" Type="String" />
                                    <asp:Parameter Name="original_CustStatus" Type="String" />
                                    <asp:Parameter Name="original_Password" Type="String" />
                                    <asp:Parameter Name="original_Email" Type="String" />
                                    <asp:Parameter Name="original_Username" Type="String" />
                                    <asp:Parameter Name="original_Contact" Type="String" />
                                </UpdateParameters>
                            </asp:SqlDataSource>
		  					</div>
                          <div class="panel-title"><h3> Add Customers</h3></div>
									
		  					<table>
                                  <tr>
                                      <td>Customer Name</td>
                                      <td><asp:TextBox ID="CustName" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="requsercustname" ControlToValidate="CustName" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                   <tr>
                                      <td>Adress</td>
                                      <td><asp:TextBox ID="CustAddress" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator1" ControlToValidate="CustAddress" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Customer D.O.B</td>
                                      <td><asp:TextBox ID="CustDOB" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator2" ControlToValidate="CustDOB" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Customer Account No.</td>
                                      <td><asp:TextBox ID="CustAccountNo" runat="server"></asp:TextBox>
                                       <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator3" ControlToValidate="CustAccountNo" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Customer NIC</td>
                                      <td><asp:TextBox ID="CustCNIC" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator4" ControlToValidate="CustCNIC" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Customer P.O Box</td>
                                      <td><asp:TextBox ID="CustPOBox" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator5" ControlToValidate="CustPOBox" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Customer City</td>
                                      <td><asp:TextBox ID="CustCity" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator6" ControlToValidate="CustCity" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Customer Status</td>
                                      <td><asp:TextBox ID="CustStatus" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator7" ControlToValidate="CustStatus" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                  <td>Password</td>
                                      <td><asp:TextBox ID="Pass" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator8" ControlToValidate="Pass" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                  <td>Email</td>
                                      <td><asp:TextBox ID="Email" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator9" ControlToValidate="Email" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Username</td>
                                      <td><asp:TextBox ID="Un" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator10" ControlToValidate="Un" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  <tr>
                                  <td>Contact</td>
                                      <td><asp:TextBox ID="Con" runat="server"></asp:TextBox>
                                      <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator11" ControlToValidate="Con" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator> 

                                      </td>
                                  </tr>
                                  
                                  
                                  <tr>
                                  <td colspan="2" align="center">
                                      <asp:Button ID="b2" runat="server" Text="Upload" OnClick="b2_Click" />
                                  </td>
                                      </tr>
		  					</table>
							
							
							</div>
		  				    
		  				
		  			</div>
  				</div>
  				
  			</div>

  			<div class="row">
  				<div class="col-md-6">
  					
  				</div>
                  </div>
                  </div>
  				


	

    <footer>
         <div class="container">
         
            <div class="copy text-center">
               OnClickEvents <a href='Welcome.aspx'>Website</a>
            </div>
            
         </div>
      </footer>

      <link href="vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>

    <script src="vendors/datatables/js/jquery.dataTables.min.js"></script>

    <script src="vendors/datatables/dataTables.bootstrap.js"></script>

    <script src="js2/custom.js"></script>
    <script src="js2/tables.js"></script>
      </form>
  </body>
</html>
