<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="emp.aspx.cs" Inherits="FypWeb.emp" %>

<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">

    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css2/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	  <form id="form1" runat="server">
  	<div class="header">
	     <div class="container">

	        <div class="row">
	           <div class="col-md-5">
	              <!-- Logo -->
	              <div class="logo">
	                 <h1><a href="index.html">Admin Panel</a></h1>
	              </div>
	           </div>
	          
	           <div class="col-md-6">
	              <div class="navbar navbar-inverse" role="banner">
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	                    <ul class="nav navbar-nav">
	                      
	                    </ul>
	                  </nav>
	              </div>
	           </div>
	        </div>
	     </div>
	</div>

    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li><a href="AdminPanel.aspx"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
                    
                    
                    <li class="submenu">
                         <a href="#">
                            <i class="glyphicon glyphicon-list"></i> Tables
                            <span class="caret pull-right"></span>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                            <li><a href="cust.aspx">Customers</a></li>
                            <li><a href="emp.aspx">Employees</a></li>
                             <li><a href="en.aspx">Entertainers</a></li>
                             <li><a href="FoodItems.aspx">Food Items</a></li>
                             <li><a href="Venues.aspx">Venues</a></li>
                             <li><a href="VenueSchedule.aspx">Venue Schedule</a></li>
                           

                        </ul>
                    </li>
                </ul>
             </div>
		  </div>
		  <div class="col-md-10">

		  	<div class="row">
  				
  					<div class="content-box-large" style="width:1000px">
		  				<div class="panel-heading">
							<div class="panel-title">Employees</div>
							
									
		  					<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="EmployeeID" DataSourceID="SqlDataSource1" GridLines="Vertical" Font-Bold="True" Font-Size="Small">
                                <AlternatingRowStyle BackColor="#DCDCDC" />
                                <Columns>
                                    <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" InsertVisible="False" ReadOnly="True" SortExpression="EmployeeID" />
                                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                                    <asp:BoundField DataField="Dob" HeaderText="Dob" SortExpression="Dob" />
                                    <asp:BoundField DataField="Cnic" HeaderText="Cnic" SortExpression="Cnic" />
                                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                                    <asp:BoundField DataField="BankAccount" HeaderText="BankAccount" SortExpression="BankAccount" />
                                    <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                                </Columns>
                                <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                                <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                                <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                <SortedAscendingHeaderStyle BackColor="#0000A9" />
                                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                <SortedDescendingHeaderStyle BackColor="#000065" />
                            </asp:GridView>
							
									
		  					<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:OnClickEventsConnectionString2 %>" DeleteCommand="DELETE FROM [Employee] WHERE [EmployeeID] = @original_EmployeeID AND [Name] = @original_Name AND [Dob] = @original_Dob AND [Cnic] = @original_Cnic AND [Address] = @original_Address AND [BankAccount] = @original_BankAccount AND [contact] = @original_contact AND [Email] = @original_Email" InsertCommand="INSERT INTO [Employee] ([Name], [Dob], [Cnic], [Address], [BankAccount], [contact], [Email]) VALUES (@Name, @Dob, @Cnic, @Address, @BankAccount, @contact, @Email)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Employee]" UpdateCommand="UPDATE [Employee] SET [Name] = @Name, [Dob] = @Dob, [Cnic] = @Cnic, [Address] = @Address, [BankAccount] = @BankAccount, [contact] = @contact, [Email] = @Email WHERE [EmployeeID] = @original_EmployeeID AND [Name] = @original_Name AND [Dob] = @original_Dob AND [Cnic] = @original_Cnic AND [Address] = @original_Address AND [BankAccount] = @original_BankAccount AND [contact] = @original_contact AND [Email] = @original_Email">
                                <DeleteParameters>
                                    <asp:Parameter Name="original_EmployeeID" Type="Int32" />
                                    <asp:Parameter Name="original_Name" Type="String" />
                                    <asp:Parameter DbType="Date" Name="original_Dob" />
                                    <asp:Parameter Name="original_Cnic" Type="Int64" />
                                    <asp:Parameter Name="original_Address" Type="String" />
                                    <asp:Parameter Name="original_BankAccount" Type="Int64" />
                                    <asp:Parameter Name="original_contact" Type="Int64" />
                                    <asp:Parameter Name="original_Email" Type="String" />
                                </DeleteParameters>
                                <InsertParameters>
                                    <asp:Parameter Name="Name" Type="String" />
                                    <asp:Parameter DbType="Date" Name="Dob" />
                                    <asp:Parameter Name="Cnic" Type="Int64" />
                                    <asp:Parameter Name="Address" Type="String" />
                                    <asp:Parameter Name="BankAccount" Type="Int64" />
                                    <asp:Parameter Name="contact" Type="Int64" />
                                    <asp:Parameter Name="Email" Type="String" />
                                </InsertParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="Name" Type="String" />
                                    <asp:Parameter DbType="Date" Name="Dob" />
                                    <asp:Parameter Name="Cnic" Type="Int64" />
                                    <asp:Parameter Name="Address" Type="String" />
                                    <asp:Parameter Name="BankAccount" Type="Int64" />
                                    <asp:Parameter Name="contact" Type="Int64" />
                                    <asp:Parameter Name="Email" Type="String" />
                                    <asp:Parameter Name="original_EmployeeID" Type="Int32" />
                                    <asp:Parameter Name="original_Name" Type="String" />
                                    <asp:Parameter DbType="Date" Name="original_Dob" />
                                    <asp:Parameter Name="original_Cnic" Type="Int64" />
                                    <asp:Parameter Name="original_Address" Type="String" />
                                    <asp:Parameter Name="original_BankAccount" Type="Int64" />
                                    <asp:Parameter Name="original_contact" Type="Int64" />
                                    <asp:Parameter Name="original_Email" Type="String" />
                                </UpdateParameters>
                            </asp:SqlDataSource>
							
									
		  					</div>
		  				    <div class="panel-title"><h3> Add Employees</h3></div>
									
		  					<table>
                                  <tr>
                                      <td> Name</td>
                                      <td><asp:TextBox ID="Name" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator19" ControlToValidate="Name" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                   <tr>
                                      <td>DOB</td>
                                      <td><asp:TextBox ID="Dob" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator18" ControlToValidate="Dob" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>NIC</td>
                                      <td><asp:TextBox ID="Nic" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator16" ControlToValidate="NIC" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Address</td>
                                      <td><asp:TextBox ID="Add" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator17" ControlToValidate="Add" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Bank Account</td>
                                      <td><asp:TextBox ID="Ba" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator13" ControlToValidate="Ba" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Contact</td>
                                      <td><asp:TextBox ID="Contact" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator14" ControlToValidate="Contact" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>Email</td>
                                      <td><asp:TextBox ID="Email" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator15" ControlToValidate="Email" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                 
                                  <tr>
                                  <td colspan="2" align="center">
                                      <asp:Button ID="b3" runat="server" Text="Upload" OnClick="b3_Click" />
                                  </td>
                                      </tr>
		  					</table>
							
							
							</div>
		  				
		  			</div>
  				</div>
  				
  			</div>

  			<div class="row">
  				<div class="col-md-6">
  					
  				</div>
                  </div>
                  </div>
  				


	

    <footer>
         <div class="container">
         
            <div class="copy text-center">
               OnClickEvents <a href='Welcome.aspx'>Website</a>
            </div>
            
         </div>
      </footer>

      <link href="vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>

    <script src="vendors/datatables/js/jquery.dataTables.min.js"></script>

    <script src="vendors/datatables/dataTables.bootstrap.js"></script>

    <script src="js2/custom.js"></script>
    <script src="js2/tables.js"></script>
      </form>
  </body>
</html>



