<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Venues.aspx.cs" Inherits="FypWeb.Venues" %>

<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">

    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css2/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	  <form id="form1" runat="server">
  	<div class="header" style="width:1500px">
	     <div class="container">
            
	        <div class="row">
	           <div class="col-md-5">
	              <!-- Logo -->
	              <div class="logo">
	                 <h1><a href="index.html">Admin Panel</a></h1>
	              </div>
	           </div>
	          
	           <div class="col-md-6">
	              <div class="navbar navbar-inverse" role="banner">
	                  <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
	                    <ul class="nav navbar-nav">
	                      
	                    </ul>
	                  </nav>
	              </div>
	           </div>
	        </div>
	     </div>
	</div>

    <div class="page-content">
    	<div class="row">
		  <div class="col-md-2">
		  	<div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li><a href="AdminPanel.aspx"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
                   
                    
                    <li class="submenu">
                         <a href="#">
                            <i class="glyphicon glyphicon-list"></i> Tables
                            <span class="caret pull-right"></span>
                         </a>
                         <!-- Sub menu -->
                         <ul>
                            <li><a href="cust.aspx">Customers</a></li>
                            <li><a href="emp.aspx">Employees</a></li>
                             <li><a href="en.aspx">Entertainers</a></li>
                             <li><a href="FoodItems.aspx">Food Items</a></li>
                             <li><a href="Venues.aspx">Venues</a></li>
                             <li><a href="VenueSchedule.aspx">Venue Schedule</a></li>
                             
                        </ul>
                    </li>
                </ul>
             </div>
		  </div>
		  <div class="col-md-10">

		  	<div class="row">
  				
  					<div class="content-box-large" style="width:1200px">
		  				<div class="panel-heading">
							<div class="panel-title">Venues 
                                <br />
                                
                            </div>
                              <br />
							
							
							
									
                            <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" DataKeyNames="VenueID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" Font-Bold="True" Font-Size="Small" OnSelectedIndexChanged="GridView3_SelectedIndexChanged">
                                <AlternatingRowStyle BackColor="#DCDCDC" />
                                <Columns>
                                    <asp:BoundField DataField="VenueID" HeaderText="VenueID" InsertVisible="False" ReadOnly="True" SortExpression="VenueID" />
                                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                                    <asp:BoundField DataField="NearestLocation" HeaderText="NearestLocation" SortExpression="NearestLocation" />
                                    <asp:BoundField DataField="Longitude" HeaderText="Longitude" SortExpression="Longitude" />
                                    <asp:BoundField DataField="Latitude" HeaderText="Latitude" SortExpression="Latitude" />
                                    <asp:BoundField DataField="Rating" HeaderText="Rating" SortExpression="Rating" />
                                    <asp:TemplateField HeaderText="Picture" SortExpression="Picture">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Picture") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Image ID="Image1" runat="server" Height="72px" ImageUrl='<%# Eval("Picture") %>' Width="79px" />
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:BoundField DataField="VenueType" HeaderText="VenueType" SortExpression="VenueType" />
                                    <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                                    <asp:BoundField DataField="PackageID" HeaderText="PackageID" SortExpression="PackageID" />
                                </Columns>
                                <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                                <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                                <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                <SortedAscendingHeaderStyle BackColor="#0000A9" />
                                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                <SortedDescendingHeaderStyle BackColor="#000065" />
                            </asp:GridView>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:OnClickEventsConnectionString2 %>" DeleteCommand="DELETE FROM [Venues] WHERE [VenueID] = @original_VenueID AND [Name] = @original_Name AND [Address] = @original_Address AND (([NearestLocation] = @original_NearestLocation) OR ([NearestLocation] IS NULL AND @original_NearestLocation IS NULL)) AND (([Longitude] = @original_Longitude) OR ([Longitude] IS NULL AND @original_Longitude IS NULL)) AND (([Latitude] = @original_Latitude) OR ([Latitude] IS NULL AND @original_Latitude IS NULL)) AND [Contact] = @original_Contact AND (([POBox] = @original_POBox) OR ([POBox] IS NULL AND @original_POBox IS NULL)) AND [Rating] = @original_Rating AND (([Picture] = @original_Picture) OR ([Picture] IS NULL AND @original_Picture IS NULL)) AND (([VenueType] = @original_VenueType) OR ([VenueType] IS NULL AND @original_VenueType IS NULL)) AND (([Price] = @original_Price) OR ([Price] IS NULL AND @original_Price IS NULL)) AND (([PackageID] = @original_PackageID) OR ([PackageID] IS NULL AND @original_PackageID IS NULL))" InsertCommand="INSERT INTO [Venues] ([Name], [Address], [NearestLocation], [Longitude], [Latitude], [Contact], [POBox], [Rating], [Picture], [VenueType], [Price], [PackageID]) VALUES (@Name, @Address, @NearestLocation, @Longitude, @Latitude, @Contact, @POBox, @Rating, @Picture, @VenueType, @Price, @PackageID)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Venues]" UpdateCommand="UPDATE [Venues] SET [Name] = @Name, [Address] = @Address, [NearestLocation] = @NearestLocation, [Longitude] = @Longitude, [Latitude] = @Latitude, [Contact] = @Contact, [POBox] = @POBox, [Rating] = @Rating, [Picture] = @Picture, [VenueType] = @VenueType, [Price] = @Price, [PackageID] = @PackageID WHERE [VenueID] = @original_VenueID AND [Name] = @original_Name AND [Address] = @original_Address AND (([NearestLocation] = @original_NearestLocation) OR ([NearestLocation] IS NULL AND @original_NearestLocation IS NULL)) AND (([Longitude] = @original_Longitude) OR ([Longitude] IS NULL AND @original_Longitude IS NULL)) AND (([Latitude] = @original_Latitude) OR ([Latitude] IS NULL AND @original_Latitude IS NULL)) AND [Contact] = @original_Contact AND (([POBox] = @original_POBox) OR ([POBox] IS NULL AND @original_POBox IS NULL)) AND [Rating] = @original_Rating AND (([Picture] = @original_Picture) OR ([Picture] IS NULL AND @original_Picture IS NULL)) AND (([VenueType] = @original_VenueType) OR ([VenueType] IS NULL AND @original_VenueType IS NULL)) AND (([Price] = @original_Price) OR ([Price] IS NULL AND @original_Price IS NULL)) AND (([PackageID] = @original_PackageID) OR ([PackageID] IS NULL AND @original_PackageID IS NULL))">
                                <DeleteParameters>
                                    <asp:Parameter Name="original_VenueID" Type="Int32" />
                                    <asp:Parameter Name="original_Name" Type="String" />
                                    <asp:Parameter Name="original_Address" Type="String" />
                                    <asp:Parameter Name="original_NearestLocation" Type="String" />
                                    <asp:Parameter Name="original_Longitude" Type="Decimal" />
                                    <asp:Parameter Name="original_Latitude" Type="Decimal" />
                                    <asp:Parameter Name="original_Contact" Type="Int64" />
                                    <asp:Parameter Name="original_POBox" Type="Int32" />
                                    <asp:Parameter Name="original_Rating" Type="Int32" />
                                    <asp:Parameter Name="original_Picture" Type="String" />
                                    <asp:Parameter Name="original_VenueType" Type="String" />
                                    <asp:Parameter Name="original_Price" Type="String" />
                                    <asp:Parameter Name="original_PackageID" Type="Int32" />
                                </DeleteParameters>
                                <InsertParameters>
                                    <asp:Parameter Name="Name" Type="String" />
                                    <asp:Parameter Name="Address" Type="String" />
                                    <asp:Parameter Name="NearestLocation" Type="String" />
                                    <asp:Parameter Name="Longitude" Type="Decimal" />
                                    <asp:Parameter Name="Latitude" Type="Decimal" />
                                    <asp:Parameter Name="Contact" Type="Int64" />
                                    <asp:Parameter Name="POBox" Type="Int32" />
                                    <asp:Parameter Name="Rating" Type="Int32" />
                                    <asp:Parameter Name="Picture" Type="String" />
                                    <asp:Parameter Name="VenueType" Type="String" />
                                    <asp:Parameter Name="Price" Type="String" />
                                    <asp:Parameter Name="PackageID" Type="Int32" />
                                </InsertParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="Name" Type="String" />
                                    <asp:Parameter Name="Address" Type="String" />
                                    <asp:Parameter Name="NearestLocation" Type="String" />
                                    <asp:Parameter Name="Longitude" Type="Decimal" />
                                    <asp:Parameter Name="Latitude" Type="Decimal" />
                                    <asp:Parameter Name="Contact" Type="Int64" />
                                    <asp:Parameter Name="POBox" Type="Int32" />
                                    <asp:Parameter Name="Rating" Type="Int32" />
                                    <asp:Parameter Name="Picture" Type="String" />
                                    <asp:Parameter Name="VenueType" Type="String" />
                                    <asp:Parameter Name="Price" Type="String" />
                                    <asp:Parameter Name="PackageID" Type="Int32" />
                                    <asp:Parameter Name="original_VenueID" Type="Int32" />
                                    <asp:Parameter Name="original_Name" Type="String" />
                                    <asp:Parameter Name="original_Address" Type="String" />
                                    <asp:Parameter Name="original_NearestLocation" Type="String" />
                                    <asp:Parameter Name="original_Longitude" Type="Decimal" />
                                    <asp:Parameter Name="original_Latitude" Type="Decimal" />
                                    <asp:Parameter Name="original_Contact" Type="Int64" />
                                    <asp:Parameter Name="original_POBox" Type="Int32" />
                                    <asp:Parameter Name="original_Rating" Type="Int32" />
                                    <asp:Parameter Name="original_Picture" Type="String" />
                                    <asp:Parameter Name="original_VenueType" Type="String" />
                                    <asp:Parameter Name="original_Price" Type="String" />
                                    <asp:Parameter Name="original_PackageID" Type="Int32" />
                                </UpdateParameters>
                            </asp:SqlDataSource>
							</div>

                          <br />
                          <br />

                           <div class="panel-title"><h3> Add Venue</h3></div>
                          <table>
                                  <tr>
                                      <td>Name</td>
                                      <td><asp:TextBox ID="Name" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator16" ControlToValidate="Name" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                   <tr>
                                      <td>Address</td>
                                      <td><asp:TextBox ID="add" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator1" ControlToValidate="add" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>NearestLocation</td>
                                      <td><asp:TextBox ID="Nl" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator2" ControlToValidate="Nl" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                               <tr>
                                      <td>Longitude</td>
                                      <td><asp:TextBox ID="longi" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator3" ControlToValidate="longi" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                               <tr>
                                      <td>Latitude</td>
                                      <td><asp:TextBox ID="lat" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator4" ControlToValidate="lat" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                               <tr>
                                      <td>Contact</td>
                                      <td><asp:TextBox ID="Con" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator5" ControlToValidate="Con" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                               <tr>
                                      <td>P.O Box</td>
                                      <td><asp:TextBox ID="Pb" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator6" ControlToValidate="Pb" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                               <tr>
                                      <td>Rating</td>
                                      <td><asp:TextBox ID="Rat" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator7" ControlToValidate="Rat" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                              <tr>
                              <td>Image </td>
                                <td>  <asp:FileUpload ID="f1" runat="server" />
                                    <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator8" ControlToValidate="f1" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                </td>
                                  <td>Venue Type</td>
                                      <td><asp:TextBox ID="vt" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator9" ControlToValidate="vt" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  <td>Price</td>
                                      <td><asp:TextBox ID="pr" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator10" ControlToValidate="pr" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                                  </tr>
                                  <tr>
                                  <td>PackagID</td>
                                      <td><asp:TextBox ID="pid" runat="server"></asp:TextBox>
                                          <asp:RequiredFieldValidator runat="server" id="RequiredFieldValidator11" ControlToValidate="pid" ErrorMessage="Please enter values" ForeColor="Red"></asp:RequiredFieldValidator>
                                      </td>
                             </tr>

                              <tr>
                                  <td colspan="2" align="center">
                                      <asp:Button ID="b2" runat="server" Text="Upload" OnClick="b2_Click" />
                                  </td>
                                      </tr>
		  					</table>
							
							
							</div>



		  				    
		  				
		  			</div>
  				</div>
  				
  			</div>

  			<div class="row">
  				<div class="col-md-6">
  					
  				</div>
                  </div>
                  </div>
  				


	

    <footer>
         <div class=" header" style="4000px">
         
            <div class="copy text-center">
               OnClickEvents <a href='#'>Website</a>
            </div>
            
         </div>
      </footer>

      <link href="vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>

    <script src="vendors/datatables/js/jquery.dataTables.min.js"></script>

    <script src="vendors/datatables/dataTables.bootstrap.js"></script>

    <script src="js2/custom.js"></script>
    <script src="js2/tables.js"></script>
      </form>
  </body>
</html>